# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(10, 10, 430, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MainLabel.setFont(font)
        self.MainLabel.setStyleSheet("background-color: rgb(56, 33, 166);\n"
"color: rgb(255, 255, 255);")
        self.MainLabel.setObjectName("MainLabel")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(20, 60, 130, 91))
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(160, 60, 130, 91))
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(300, 60, 130, 91))
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(20, 160, 130, 91))
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(300, 160, 130, 91))
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(160, 160, 130, 91))
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(20, 260, 130, 91))
        self.btn_7.setObjectName("btn_7")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(300, 260, 130, 91))
        self.btn_9.setObjectName("btn_9")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(160, 260, 130, 91))
        self.btn_8.setObjectName("btn_8")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(20, 360, 201, 131))
        self.btn_0.setObjectName("btn_0")
        self.bnt_equal = QtWidgets.QPushButton(self.centralwidget)
        self.bnt_equal.setGeometry(QtCore.QRect(240, 360, 191, 131))
        self.bnt_equal.setStyleSheet("background-color: rgb(105, 255, 153);")
        self.bnt_equal.setObjectName("bnt_equal")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(430, 70, 65, 70))
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(430, 150, 65, 70))
        self.btn_minus.setObjectName("btn_minus")
        self.btn_mno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mno.setGeometry(QtCore.QRect(430, 230, 65, 70))
        self.btn_mno.setObjectName("btn_mno")
        self.btn_dil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dil.setGeometry(QtCore.QRect(430, 310, 65, 70))
        self.btn_dil.setObjectName("btn_dil")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.AddFunc()
        self.IsEqual = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.MainLabel.setText(_translate("MainWindow", "0"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.bnt_equal.setText(_translate("MainWindow", "="))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_mno.setText(_translate("MainWindow", "*"))
        self.btn_dil.setText(_translate("MainWindow", "/"))

    def AddFunc(self):
        self.btn_0.clicked.connect(lambda: self.WriteNum(self.btn_0.text()))
        self.btn_1.clicked.connect(lambda: self.WriteNum(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.WriteNum(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.WriteNum(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.WriteNum(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.WriteNum(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.WriteNum(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.WriteNum(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.WriteNum(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.WriteNum(self.btn_9.text()))
        self.btn_plus.clicked.connect(lambda: self.WriteNum(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.WriteNum(self.btn_minus.text()))
        self.btn_mno.clicked.connect(lambda: self.WriteNum(self.btn_mno.text()))
        self.btn_dil.clicked.connect(lambda: self.WriteNum(self.btn_dil.text()))

        self.bnt_equal.clicked.connect(lambda: self.Resoult())

    def Resoult(self):
        try:
            DetailsInfo = (
                "Ви нажали кнопку, нічого не вевши. Необхідно виконати хоть 1 дію щоб все виконувалось коректно!"
            )

            if not self.IsEqual:
                res = eval(self.MainLabel.text())
                self.MainLabel.setText(f"Результат: {res}")
                self.IsEqual = True
            else:
                error = QMessageBox()
                error.setWindowTitle("Error")
                error.setText("Поле пусте, зараз не можна виконати цю дію.")
                error.setIcon(QMessageBox.Warning)
                error.setStandardButtons(QMessageBox.Ok)

                error.setInformativeText("Два рази не можна виконати дію.")
                error.setDetailedText(DetailsInfo)


                self.PressOk = error.exec_()

                if self.PressOk == QMessageBox.Ok:
                    self.MainLabel.setText("")
                    self.IsEqual = False
        except Exception as e:
            print(e)


    def WriteNum(self, number):
        if self.MainLabel.text() == "0" or self.MainLabel.text() == "" or self.IsEqual == True:
            self.MainLabel.setText(number)
            self.IsEqual = False
        else:
            self.MainLabel.setText(self.MainLabel.text() + number)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
