# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(600, 600)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setStyleSheet("background-color: #5a6779\n"
                "")
                self.centralwidget.setObjectName("centralwidget")
                self.MainLabel = QtWidgets.QLabel(self.centralwidget)
                self.MainLabel.setGeometry(QtCore.QRect(10, 10, 581, 61))
                font = QtGui.QFont()
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.MainLabel.setFont(font)
                self.MainLabel.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 15px;\n"
                "color: #ffffff")
                self.MainLabel.setObjectName("MainLabel")
                self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_1.setGeometry(QtCore.QRect(20, 80, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_1.setFont(font)
                self.btn_1.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_1.setObjectName("btn_1")
                self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_4.setGeometry(QtCore.QRect(20, 200, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_4.setFont(font)
                self.btn_4.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_4.setObjectName("btn_4")
                self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_5.setGeometry(QtCore.QRect(170, 200, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_5.setFont(font)
                self.btn_5.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_5.setObjectName("btn_5")
                self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_7.setGeometry(QtCore.QRect(20, 310, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_7.setFont(font)
                self.btn_7.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_7.setObjectName("btn_7")
                self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_2.setGeometry(QtCore.QRect(170, 80, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_2.setFont(font)
                self.btn_2.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_2.setObjectName("btn_2")
                self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
                self.btn_equal.setGeometry(QtCore.QRect(320, 430, 130, 120))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_equal.setFont(font)
                self.btn_equal.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_equal.setObjectName("btn_equal")
                self.btn_str = QtWidgets.QPushButton(self.centralwidget)
                self.btn_str.setGeometry(QtCore.QRect(20, 430, 130, 100))
                self.btn_str.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "font-size: 26px;\n"
                "font-weight: bold;"
                "color: #ffffff")
                self.btn_str.setObjectName("btn_str")
                self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_0.setGeometry(QtCore.QRect(170, 430, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_0.setFont(font)
                self.btn_0.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_0.setObjectName("btn_0")
                self.btn_multip = QtWidgets.QPushButton(self.centralwidget)
                self.btn_multip.setGeometry(QtCore.QRect(470, 300, 120, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_multip.setFont(font)
                self.btn_multip.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_multip.setObjectName("btn_multip")
                self.btn_div = QtWidgets.QPushButton(self.centralwidget)
                self.btn_div.setGeometry(QtCore.QRect(470, 420, 120, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_div.setFont(font)
                self.btn_div.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_div.setObjectName("btn_div")
                self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
                self.btn_minus.setGeometry(QtCore.QRect(470, 190, 120, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_minus.setFont(font)
                self.btn_minus.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_minus.setObjectName("btn_minus")
                self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
                self.btn_plus.setGeometry(QtCore.QRect(470, 80, 120, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_plus.setFont(font)
                self.btn_plus.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_plus.setObjectName("btn_plus")
                self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_6.setGeometry(QtCore.QRect(320, 200, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_6.setFont(font)
                self.btn_6.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_6.setObjectName("btn_6")
                self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_3.setGeometry(QtCore.QRect(320, 80, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_3.setFont(font)
                self.btn_3.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_3.setObjectName("btn_3")
                self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_9.setGeometry(QtCore.QRect(320, 310, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_9.setFont(font)
                self.btn_9.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_9.setObjectName("btn_9")
                self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
                self.btn_8.setGeometry(QtCore.QRect(170, 310, 130, 100))
                font = QtGui.QFont()
                font.setPointSize(26)
                font.setBold(True)
                font.setWeight(75)
                self.btn_8.setFont(font)
                self.btn_8.setStyleSheet("background-color: #38636b;\n"
                "border-radius: 10px;\n"
                "color: #ffffff")
                self.btn_8.setObjectName("btn_8")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
                self.menubar.setObjectName("menubar")
                self.menuApp = QtWidgets.QMenu(self.menubar)
                self.menuApp.setObjectName("menuApp")
                MainWindow.setMenuBar(self.menubar)
                self.actionExit = QtWidgets.QAction(MainWindow)
                self.actionExit.setObjectName("actionExit")
                self.actionGit = QtWidgets.QAction(MainWindow)
                self.actionGit.setObjectName("actionGit")
                self.menuApp.addAction(self.actionExit)
                self.menuApp.addSeparator()
                self.menuApp.addAction(self.actionGit)
                self.menubar.addAction(self.menuApp.menuAction())

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                self.AddFunc()
                self.IsEqual = False

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.MainLabel.setText(_translate("MainWindow", "0"))
                self.btn_1.setText(_translate("MainWindow", "1"))
                self.btn_4.setText(_translate("MainWindow", "4"))
                self.btn_5.setText(_translate("MainWindow", "5"))
                self.btn_7.setText(_translate("MainWindow", "7"))
                self.btn_2.setText(_translate("MainWindow", "2"))
                self.btn_equal.setText(_translate("MainWindow", "="))
                self.btn_str.setText(_translate("MainWindow", "clear"))
                self.btn_0.setText(_translate("MainWindow", "0"))
                self.btn_multip.setText(_translate("MainWindow", "*"))
                self.btn_div.setText(_translate("MainWindow", "/"))
                self.btn_minus.setText(_translate("MainWindow", "-"))
                self.btn_plus.setText(_translate("MainWindow", "+"))
                self.btn_6.setText(_translate("MainWindow", "6"))
                self.btn_3.setText(_translate("MainWindow", "3"))
                self.btn_9.setText(_translate("MainWindow", "9"))
                self.btn_8.setText(_translate("MainWindow", "8"))
                self.menuApp.setTitle(_translate("MainWindow", "App"))
                self.actionExit.setText(_translate("MainWindow", "Exit"))
                self.actionGit.setText(_translate("MainWindow", "Git"))

        def AddFunc(self):
                self.btn_0.clicked.connect(lambda: self.WriteNum(self.btn_0.text()))
                self.btn_1.clicked.connect(lambda: self.WriteNum(self.btn_1.text()))
                self.btn_2.clicked.connect(lambda: self.WriteNum(self.btn_2.text()))
                self.btn_3.clicked.connect(lambda: self.WriteNum(self.btn_3.text()))
                self.btn_4.clicked.connect(lambda: self.WriteNum(self.btn_4.text()))
                self.btn_5.clicked.connect(lambda: self.WriteNum(self.btn_5.text()))
                self.btn_6.clicked.connect(lambda: self.WriteNum(self.btn_6.text()))
                self.btn_7.clicked.connect(lambda: self.WriteNum(self.btn_7.text()))
                self.btn_8.clicked.connect(lambda: self.WriteNum(self.btn_8.text()))
                self.btn_9.clicked.connect(lambda: self.WriteNum(self.btn_9.text()))
                self.btn_plus.clicked.connect(lambda: self.WriteNum(self.btn_plus.text()))
                self.btn_minus.clicked.connect(lambda: self.WriteNum(self.btn_minus.text()))
                self.btn_multip.clicked.connect(lambda: self.WriteNum(self.btn_multip.text()))
                self.btn_div.clicked.connect(lambda: self.WriteNum(self.btn_div.text()))

                self.btn_equal.clicked.connect(lambda: self.Resoult())
                self.btn_str.clicked.connect(lambda: self.ClearLabel())

        def WriteNum(self, number: str):
                if self.MainLabel.text() == "0" or self.MainLabel.text() == "" or self.IsEqual == True:
                      self.MainLabel.setText(number)
                      self.IsEqual == False
                else:
                      self.MainLabel.setText(self.MainLabel.text() + number)


        def Resoult(self):
                DetailsInfo = (
                       "Ви нажали кнопку, нічого не вевши. Необхідно виконати хоть 1 дію щоб все виконувалось коректно!"
                )
                try:
                        if self.MainLabel.text() == "Результат: 0" or self.MainLabel.text() == "0":
                               ErrorMsg = QMessageBox()
                               ErrorMsg.setWindowTitle("Error")
                               ErrorMsg.setText("Поле пусте, зараз не можна виконати цю дію.")
                               ErrorMsg.setIcon(QMessageBox.Warning)
                               ErrorMsg.setStandardButtons(QMessageBox.Ok)

                               ErrorMsg.setDetailedText(DetailsInfo)

                               self.PressOk = ErrorMsg.exec_()

                               if self.PressOk == QMessageBox.Ok:
                                      self.MainLabel.setText("0")
                                      self.IsEqual = False
                                      return

                        if not self.IsEqual: 
                                Res = eval(self.MainLabel.text())
                                self.MainLabel.setText(f"Результат: {Res}")
                                self.IsEqual = True
                                return

                except Exception as e:
                       print(e)

        def ClearLabel(self):
               self.MainLabel.setText("0")
               self.IsEqual = False

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
